{% set name = "dgl" %}
{% set version = "2.4.0" %}
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/dmlc/dgl/archive/v{{ version }}.tar.gz
    sha256: 6372d0c804b52940f2a4d0f9b9d83c422ec5ef933907b2805da08b409f8ed26c
    patches:
      - patches/0001-fix-clang-errors.patch
      - patches/0002-fix-libdgl-sparse-pytorch-location-logic.patch
      - patches/0003-control-make-parallelism.patch
      - patches/0004-Use-system-liburing.patch                          # [linux]
      - patches/0005-Don-t-add-post-version-to-graphbolt-lib.patch

  - folder: third_party/googletest
    git_url: https://github.com/google/googletest.git
    git_rev: f8d7d77c06936315286eb55f8de22cd23c188571

  - folder: third_party/libxsmm
    git_url: https://github.com/hfp/libxsmm.git
    git_rev: 80090603e43f6ddc870cc42e1403dd0af07744cc

  - folder: third_party/pcg
    git_url: https://github.com/imneme/pcg-cpp.git
    git_rev: 428802d1a5634f96bcd0705fab379ff0113bcf13

  - folder: third_party/cccl
    git_url: https://github.com/NVIDIA/cccl.git
    git_rev: 69be18c0232c9dddaae6c715aa9ed1b61bfb10be

  - folder: third_party/cuco
    git_url: https://github.com/NVIDIA/cuCollections.git
    git_rev: 6c0d7ee190a167c6976af0f7c628a43d13b78f38

build:
  skip: true  # [win or py<39]
  # pytorch 2.5 builds in conda-forge do not support CUDA 11.8 anymore
  skip: true  # [cuda_compiler_version == "11.8"]
  number: 0
  rpaths:
    - lib/
      # PyTorch libs are in site-packages instead of with other shared objects
    - {{ SP_DIR }}/torch/lib/
      # DGL libs are in site-packages instead of with other shared objects
    - {{ SP_DIR }}/dgl/
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux64]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  ignore_run_exports:
    - gklib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - pytorch                                # [build_platform != target_platform]
    - pytorch =*=*{{ torch_proc_type }}*     # [build_platform != target_platform]
    - libtorch                               # [build_platform != target_platform]
    - cmake >=3.20
    - git
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
    - {{ compiler('cxx') }}
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version not in (undefined, 'None')]
    - cudnn                                     # [cuda_compiler_version not in (undefined, 'None')]
    - cython <3
    - dlpack ==0.7
    - dmlc ==0.5
    - gklib ==5.1.1  # https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5396#issuecomment-1900607226
    - libblas
    - libcublas-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev       # [(cuda_compiler_version or "").startswith("12")]
    - libcurand-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcusolver-dev    # [(cuda_compiler_version or "").startswith("12")]
    - libcusparse-dev    # [(cuda_compiler_version or "").startswith("12")]
    - cuda-cudart-dev    # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvrtc-dev     # [(cuda_compiler_version or "").startswith("12")]
    - cuda-nvtx-dev      # [(cuda_compiler_version or "").startswith("12")]
    - libcblas
    - liblapack
    - liblapacke
    - liburing  # [linux]
    - metis ==5.1.1
    - nanoflann <=1.4.2
    - parallel-hashmap
    - python
    - pip
    - libtorch
    - pytorch  # duplicate dep to pick up conda-forge pinnings
    - pytorch =*=*{{ torch_proc_type }}*
    - setuptools
  run:
    - networkx >=2.1
    - numpy >=1.14.0
    - pandas  # not a core dependency, but leaks in the 'import dgl' test via dgl.data 
    - psutil >=5.8.0
    - python
    - {{ pin_compatible("pytorch", max_pin="x.x.x") }}  # ensure libgraphbolt compatibility
    - pytorch =*=*{{ torch_proc_type }}*
    - requests >=2.19.0
    - scipy >=1.1.0
    - tensorflow
    - torchdata >=0.5.0
    - tqdm
    - pyyaml
    - pydantic

test:
  requires:
    - pip
    - pyyaml
    - pydantic
  imports:
    - dgl
    - dgl.sparse
  commands:
    - pip check || true  # Get the output of pip check but don't care if it fails
    - python -c "import dgl"

about:
  home: https://github.com/dmlc/dgl
  license: Apache-2.0
  license_file:
    - LICENSE
    - third_party/pcg/LICENSE-APACHE.txt
    - third_party/pcg/LICENSE-MIT.txt
    - third_party/libxsmm/LICENSE.md
    - third_party/cccl/LICENSE
    - HugeCTR_gpu_cache_license.txt
  summary: A deep graph library
  description: |
    DGL is an easy-to-use, high performance and scalable Python package for deep
     learning on graphs. DGL is framework agnostic, meaning if a deep graph
     model is a component of an end-to-end application, the rest of the logics
     can be implemented in any major frameworks, such as PyTorch, Apache MXNet
     or TensorFlow.
  doc_url: https://docs.dgl.ai/en/latest/

extra:
  recipe-maintainers:
    - frozenbugs
    - mikemhenry
    - hmacdope
    - zklaus
